# This file specifies your Python application's runtime configuration
# including URL routing, versions, static file uploads, etc. See
# https://developers.google.com/appengine/docs/python/config/appconfig
# for details.

runtime: python27
api_version: 1
threadsafe: yes
skip_files:
- node_modules/.*
- public/.*
- src/.*
- .git/*

# Handlers define how to route requests to your application.
handlers:

# each dynamic API path needs to be called out since .* goes to the react app, which is laregly static served
- url: /search.*  # search api
  script: main.app

- url: /proxy.*  # amazon api proxy
  script: main.app


- url: /mail.*  # send mail
  script: main.app

# App Engine serves and caches static files contained in the listed directories
# (and subdirectories). Uncomment and set the directory as needed.
- url: /
  static_files: build/index.html
  upload: build/index.html
  secure: always

- url: /whatsgood/(.*)
  static_files: build/\1
  upload: build/(.*)

- url: /img/(.*)
  static_files: build/img/\1
  upload: build/img/(.*)

- url: /(.*\.(css))$
  static_files: build/\1
  upload: build/.*\.(css)$

- url: /(.*)
  static_files: build/index.html
  upload: build/index.html

# deferred execution queue setup
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

# Third party libraries that are included in the App Engine SDK must be listed
# here if you want to use them.  See
# https://developers.google.com/appengine/docs/python/tools/libraries27 for
# a list of libraries included in the SDK.  Third party libs that are *not* part
# of the App Engine SDK don't need to be listed here, instead add them to your
# project directory, either as a git submodule or as a plain subdirectory.
# TODO: List any other App Engine SDK libs you may need here.
libraries:
- name: lxml
  version: latest

- name: ssl
  version: latest


builtins:
- deferred: on
