export const USERS_PATH = '/users'
export const USERNAMES_TO_USERIDS_PATH = '/usernames-to-userids'
export const FOLLOWERS_PATH = '/followers'
export const FOLLOWINGS_PATH = '/followings'
export const SUBJECTS_PATH = '/subjects'
export const REVIEWS_PATH = '/reviews'